function simulateSPADe(pipelined,CONTROLLER_TYPE,h,TAU_WORKLOAD_SCENARIOS,phi,Gamma,C_aug,K,F,PATTERN,SIMULATION_TIME,REFERENCE,SYSTEM_MODEL,fh,FEEDFORWARD,REFERENCE_STATE)
%% Choose the correct simulation
if pipelined==1
    simulateSPADePipelined(h,TAU_WORKLOAD_SCENARIOS,phi,Gamma,C_aug,K,F,PATTERN,SIMULATION_TIME,REFERENCE,SYSTEM_MODEL,CONTROLLER_TYPE,FEEDFORWARD,REFERENCE_STATE); 
else %non-pipelined
    simulateSPADeNonPipelined(h,TAU_WORKLOAD_SCENARIOS,phi,Gamma,C_aug,K,F,PATTERN,SIMULATION_TIME,fh,REFERENCE,SYSTEM_MODEL,CONTROLLER_TYPE,FEEDFORWARD,REFERENCE_STATE);
end